create table if not exists public.scans (
  id bigint generated by default as identity primary key,
  student_id text not null unique,
  scanned_at timestamptz not null default timezone('utc', now()),
  source text not null default 'camera',
  constraint scans_source_check check (source in ('camera', 'manual', 'sync'))
);
